// Package inner provides inner-proof generators / loaders for the wrapper.
//
//   - cubic.go    — dev fixture: trivial x³+x+5==y BN254 Groth16, generated in-process.
//   - risc0.go    — real input: snarkjs JSON triple loaded via the parser package.
package inner

import (
	"fmt"
	"math/big"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/backend/witness"
	"github.com/consensys/gnark/constraint"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
	stdgroth16 "github.com/consensys/gnark/std/recursion/groth16"
)

// CubicCircuit defines x^3 + x + 5 == y over BN254.
//
// X is private, Y is public. The witness pair (x=3, y=35) satisfies it.
type CubicCircuit struct {
	X frontend.Variable
	Y frontend.Variable `gnark:",public"`
}

// Define enforces x*x*x + x + 5 == y.
func (c *CubicCircuit) Define(api frontend.API) error {
	x3 := api.Mul(c.X, c.X, c.X)
	api.AssertIsEqual(api.Add(x3, c.X, 5), c.Y)
	return nil
}

// Compile-time assertion that CubicCircuit satisfies frontend.Circuit.
var _ frontend.Circuit = (*CubicCircuit)(nil)

// GenerateCubicSetup compiles the cubic circuit over BN254 and runs a
// single-party (INSECURE) Groth16 setup. Toxic waste is generated by gnark
// internally and discarded; we never log or persist anything beyond pk/vk.
// The returned ccs / pk / vk are intended to be persisted by `setup` and
// re-loaded by `prove`.
func GenerateCubicSetup() (
	constraint.ConstraintSystem,
	groth16.ProvingKey,
	groth16.VerifyingKey,
	error,
) {
	ccs, err := frontend.Compile(
		ecc.BN254.ScalarField(),
		r1cs.NewBuilder,
		&CubicCircuit{},
	)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("compile cubic: %w", err)
	}
	pk, vk, err := groth16.Setup(ccs)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("setup cubic: %w", err)
	}
	return ccs, pk, vk, nil
}

// ProveCubic builds a BN254 Groth16 proof for the cubic circuit.
//
// outerField is the field of the outer (verifier) circuit — for our wrapper
// it is BLS12-381's scalar field. Passing it via GetNativeProverOptions
// keeps the inner proof's hash-to-field formatting compatible with the
// downstream in-circuit verifier (which would otherwise reject the proof).
func ProveCubic(
	ccs constraint.ConstraintSystem,
	pk groth16.ProvingKey,
	x, y *big.Int,
	outerField *big.Int,
) (groth16.Proof, witness.Witness, error) {
	full, err := frontend.NewWitness(
		&CubicCircuit{X: x, Y: y},
		ecc.BN254.ScalarField(),
	)
	if err != nil {
		return nil, nil, fmt.Errorf("new full witness: %w", err)
	}
	pub, err := full.Public()
	if err != nil {
		return nil, nil, fmt.Errorf("extract public witness: %w", err)
	}
	proof, err := groth16.Prove(
		ccs, pk, full,
		stdgroth16.GetNativeProverOptions(outerField, ecc.BN254.ScalarField()),
	)
	if err != nil {
		return nil, nil, fmt.Errorf("prove cubic: %w", err)
	}
	return proof, pub, nil
}

// VerifyCubicNative runs the native (non-recursive) Groth16 verify on a
// cubic-circuit proof. We must never proceed to outer-prove on an inner
// proof we haven't first validated natively.
func VerifyCubicNative(
	proof groth16.Proof,
	vk groth16.VerifyingKey,
	pub witness.Witness,
	outerField *big.Int,
) error {
	if err := groth16.Verify(
		proof, vk, pub,
		stdgroth16.GetNativeVerifierOptions(outerField, ecc.BN254.ScalarField()),
	); err != nil {
		return fmt.Errorf("native verify cubic: %w", err)
	}
	return nil
}
